### ISSUE TITLE
Techniques to rat?

### ISSUE THREAD

**Issue by ghost** [Blank-c/BlankOBF#12]

**Comment by Blank-c** [comment]
I don't use Discord, but I use Telegram. If you wish, you can join my group. The link is at the bottom of the readme of my other project `Blank Grabber`.

You can ask your questions there, people might help.

**Comment by applebytez** [comment]
Beautiful... Beautiful mr. blanc. Proving your case that you definitely are not a malicious man at all!

**Comment by Blank-c** [comment]
I take that as a thanks.

**Comment by applebytez** [comment]
You should take it as you're an asshole... You have no morals.

**Comment by Blank-c** [comment]
🐢

**Comment by DARKNOSY** [comment]
lmfao

**Comment by applebytez** [comment]
> lmfao

<img width="230" alt="image" src="https://github.com/Blank-c/BlankOBF/assets/129020795/eb940f3c-9a58-429b-a10e-84829e4340fb">
hdf

**Comment by DARKNOSY** [comment]
Can't you read "main languages"

![image](https://github.com/Blank-c/BlankOBF/assets/109553205/1b8887c4-266d-4619-96fc-776bfdfe7534)

**Comment by applebytez** [comment]
I can read and they tell me 'script kiddie'

**Comment by 5orai** [comment]
bump! how do I rat

**Comment by DARKNOSY** [comment]
lmfao what did I even do to you lil bro
