### ISSUE TITLE
Deobfuscator

### ISSUE THREAD

**Issue by Fadi002** [Blank-c/BlankOBF#15]
https://github.com/Fadi002/BlankOBF-deobfuscator

**Comment by dfgszdgzsdgszdgzsdgzsadgzsadgszgd** [comment]
Might be patched as of 10/2/2023

**Comment by Fadi002** [comment]
> Might be patched as of 10/2/2023

he didn't even update his obfuscator lol

**Comment by Aculia** [comment]
Yeah my bad lol, someone sent me a file with this github repo and I wanted to read in and the obfuscation in the file looked completely different from the one this gives now that I run it

**Comment by dfgszdgzsdgszdgzsdgzsadgzsadgszgd** [comment]
> > Might be patched as of 10/2/2023
> 
> he ddn't even update his obfuscator lol

Yeah my bad lol, someone sent me a file with this github repo and I wanted to read in and the obfuscation in the file looked completely different from the one this gives now that I run it
