### ISSUE TITLE
Yet another deobfuscator

### ISSUE THREAD

**Issue by ptrstr** [Blank-c/BlankOBF#16]
https://github.com/ptrstr/DeBlankOBF

**Comment by gumbobrot** [comment]
HAHHAHA ☠️ 

i love you bro ❤️

**Comment by dfgszdgzsdgszdgzsdgzsadgzsadgszgd** [comment]
C:\Users\NONAME>python Saver.py evil.py output.pyc
Traceback (most recent call last):
  File "C:\Users\NONAME\Saver.py", line 65, in <module>
    stage2 = undo_stage3(stage3)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NONAME\Saver.py", line 50, in undo_stage3
    re.findall(rb"base64.b64decode\(b'([A-Za-z0-9+/=]+)'\)", data)[0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

C:\Users\NONAME>

**Comment by ptrstr** [comment]
> C:\Users\NONAME>python Saver.py evil.py output.pyc Traceback (most recent call last): File "C:\Users\NONAME\Saver.py", line 65, in stage2 = undo_stage3(stage3) ^^^^^^^^^^^^^^^^^^^ File "C:\Users\NONAME\Saver.py", line 50, in undo_stage3 re.findall(rb"base64.b64decode(b'([A-Za-z0-9+/=]+)')", data)[0] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^ IndexError: list index out of range
> 
> C:\Users\NONAME>

Could you send me that script?

**Comment by Aculia** [comment]
If you are talking about Saver.py it's the de-obfuscator

**Comment by dfgszdgzsdgszdgzsdgzsadgzsadgszgd** [comment]
> > C:\Users\NONAME>python Saver.py evil.py output.pyc Traceback (most recent call last): File "C:\Users\NONAME\Saver.py", line 65, in stage2 = undo_stage3(stage3) ^^^^^^^^^^^^^^^^^^^ File "C:\Users\NONAME\Saver.py", line 50, in undo_stage3 re.findall(rb"base64.b64decode(b'([A-Za-z0-9+/=]+)')", data)[0] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^ IndexError: list index out of range
> > C:\Users\NONAME>
> 
> Could you send me that script?

If you are talking about Saver.py it's the de-obfuscator

**Comment by dfgszdgzsdgszdgzsdgzsadgzsadgszgd** [comment]
> > > C:\Users\NONAME>python Saver.py evil.py output.pyc Traceback (most recent call last): File "C:\Users\NONAME\Saver.py", line 65, in stage2 = undo_stage3(stage3) ^^^^^^^^^^^^^^^^^^^ File "C:\Users\NONAME\Saver.py", line 50, in undo_stage3 re.findall(rb"base64.b64decode(b'([A-Za-z0-9+/=]+)')", data)[0] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^ IndexError: list index out of range
> > > C:\Users\NONAME>
> > 
> > 
> > Could you send me that script?
> 
> If you are talking about Saver.py it's the de-obfuscator

evil.py was print("Hello There!")
Also as I'm re-running it nothing is even getting sent to the output.pyc file

**Comment by Varunkusi** [comment]
while executing the obfuscated file the jupyter kernel is getting crashed ? why?
