### ISSUE TITLE
Detections

### ISSUE THREAD

**Issue by dfgszdgzsdgszdgzsdgzsadgzsadgszgd** [Blank-c/BlankOBF#17]
COMPILED TO EXE WITH PYINSTALLER
![Screenshot 2023-10-07 161634](https://github.com/Blank-c/BlankOBF/assets/137090888/d46cffdc-6c99-4470-9254-146f84b180f3)

**Comment by dfgszdgzsdgszdgzsdgzsadgzsadgszgd** [comment]
Any possible way to lower the detections like all that file does is print("Hello there !") not sure if it's pyinstaller or obfuscator

**Comment by Blank-c** [comment]
> Any possible way to lower the detections like all that file does is print("Hello there !") not sure if it's Pyinstaller or obfuscator

I am pretty sure its PyInstaller. I haven't seen many Pyinstaller packed programs that are FUD.
