### ISSUE TITLE
Hey Blank you have telegram or discord i need your help with blank grabber plsssssssss

### ISSUE THREAD

**Issue by dusdvlq** [Blank-c/BlankOBF#19]
plsss

**Comment by Blank-c** [comment]
The project is currently on a hiatus.

**Comment by dusdvlq** [comment]
alr ye the password doesnt work on the rar file like blank and blank123 i saw the hash to i encrypted the hash didnt work too
thats why but if the tool works again or idk just gimme ur telegram name we can write

**Comment by Blank-c** [comment]
Telegram: BlankGC
The password should be in the config file.
