### ISSUE TITLE
error line 9

### ISSUE THREAD

**Issue by newMet4s** [Blank-c/BlankOBF#26]
Traceback (most recent call last):
  File "C:\Users\d\Downloads\Blank-Grabber-main\Blank Grabber\env\Scripts\process.py", line 9, in <module>
    import pyaes
ModuleNotFoundError: No module named 'pyaes'
"pyinstaller"is not internal or external
A command, an executable program, or a batch file.
I've already done these steps:pip install pyaes and python -m pip install pyaes
and also I changed the folder path in PATH but it didn't help

**Comment by Blank-c** [comment]
Question not related to the repo.

possible fix: `python -m pip install --upgrade pyinstaller pyaesm`
