### ISSUE TITLE
blank grabber

### ISSUE THREAD

**Issue by Astraaexe** [Blank-c/BlankOBF#27]
sorry it's not related to this project but when I create the grabber this message appears even though pyaes is installed. I've been looking for two days in the blank grabber project issues but I can't find anything. I also tried to delete the env folder but it reinstalls when I restart the creation. plsssss help me
![Capture d'écran 2024-07-18 195241](https://github.com/user-attachments/assets/93a6c6fa-edbf-4268-97ed-8f93b446d219)

**Comment by Blank-c** [comment]
I am not continuing the project anymore, though this is not concrete.

It looks like a file is missing. You may try to re-download it, and/or run it on another system or in a Windows Sandbox. However, I believe you should use something else since BG appears to be dead.

**Comment by rohanraj-aipro** [comment]
I've faced the same problem. I ran it on another Different computer.
Discord for more doubts regarding Blank Grabber:
Discord ID:-    rohan018721

**Comment by Blank-c** [comment]
Uninstall current python and install python 3.11.
I wouldn't recommend you use the project, its outdated.

**Comment by rohanraj-aipro** [comment]
You're recommending us to Not use Blank Grabber anymore, because it's Outdated?? Doesn't matter i gues...

**Comment by Crypter-4u** [comment]
@Blank-c  did you mean, to make us avoid Blank Grabber cause it's outdated?

**Comment by Blank-c** [comment]
@Crypter-4u yes

**Comment by Blank-c** [comment]
> You're recommending us to Not use Blank Grabber anymore, because it's Outdated?? Doesn't matter i gues...

Discord or some browser may patch the encryption of passwords and outdated stealer will not be able to retrive them.
