### ISSUE TITLE
    match choice:           ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by rohanraj-aipro** [Blank-c/BlankOBF#30]
```
Traceback (most recent call last):
  File "C:\Users\Rohan\Desktop\prin_ceofland.py", line 1, in <module>
    from BlankOBFv2 import BlankOBFv2
  File "C:\Users\Rohan\AppData\Local\Programs\Python\Python39\lib\BlankOBFv2.py", line 204
    match choice:
          ^
SyntaxError: invalid syntax

Process finished with exit code 1

```

**What i did was, I copied your BlankOBFv2.py to this location:-** 
`C:\Users\Rohan\AppData\Local\Programs\Python\Python39\lib\BlankOBFv2.py
`
**So that, i can directly import it in Pycharm. Now, im getting the above error. What can i do?**

**Comment by Blank-c** [comment]
What is the output of `python --version` in the console?

**Comment by Blank-c** [comment]
The `match` statement is introduced in python 3.10, and from your path, I am assuming you are using python 3.9.

You need to upgrade to the newer version.

**Comment by rohanraj-aipro** [comment]
Ohhk. Thanks
