### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by LocalsGitHub** [Blank-c/BlankOBF#4]
why did you obfuscate the obfuscator especially when all it takes is decoding base64 lmfao
[output10.txt](https://github.com/Blank-c/BlankOBF/files/8457223/output10.txt)

**Comment by Blank-c** [comment]
> why did you obfuscate the obfuscator especially when all it takes is decoding base64 lmfao [output10.txt](https://github.com/Blank-c/BlankOBF/files/8457223/output10.txt)

Thought of releasing source code, but exams are going so got no time

**Comment by LocalsGitHub** [comment]
that doesn't make sense, what do exams have to do with anything, you just have to upload the original source code which I actually already did. if your not going to provide it in the original repo at least keep this issue open so that anyone can download it

**Comment by LocalsGitHub** [comment]
code --->
[sourcecode.txt](https://github.com/Blank-c/BlankOBF/files/8457338/sourcecode.txt)

**Comment by Blank-c** [comment]
> that doesn't make sense, what do exams have to do with anything, you just have to upload the original source code which I actually already did. if your not going to provide it in the original repo at least keep this issue open so that anyone can download it

I cannot use my pc during exams and the source code is in it.

**Comment by Blank-c** [comment]
> code ---> [sourcecode.txt](https://github.com/Blank-c/BlankOBF/files/8457338/sourcecode.txt)

I will post source code after exams
