### ISSUE TITLE
De obfuscate

### ISSUE THREAD

**Issue by user-take** [Blank-c/BlankOBF#8]
Someone made a very malicious script with this obfuscator, can you help deobfuscate it?

**Comment by Blank-c** [comment]
This script uses python byte code, so the final layer cannot be deobfuscated manually. You need to use tools like decompyle3 or uncompyle6 but both of them are outdated as of now.

**Comment by user-take** [comment]
can you just decompile the script that i will give ?

**Comment by Blank-c** [comment]
> can you just decompile the script that i will give ?

Like I said I cannot "decompile" the script, but I could try something (still very low chance of success) if you want. DM me the script on discord: Blank?#0886
